# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0241ea5b129bac3505841d38c459b2b68440913887d6f8850dc3acdc2e44ec2d28144bacd9450582f07612f1da93134c83d48f5581ba6c7886bb5b836f3499f

test:
  secret_key_base: d041e6632aa769231d63e3496d669d195a4102f32293a476b961ffb3448b161d964f1aeaec957ba2655eab08188f5c9fa08700750a65de3894d57149f8ca1b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
